### ISSUE TITLE
Missing words in dictionary

### ISSUE THREAD

**Issue by mkordas** [webdizz/sonarqube-spellcheck#21]
I miss at least the following words in the default dictionary:
* acked
* aop
* arities
* autowired
* autowiring
* bloomberg
* bst
* cacheable
* castable
* copiable
* confirmable
* csv
* descoped
* droppable
* eligible
* enrichers
* iterable
* iterables
* joda
* multimap
* notionals
* nullable
* pollers
* proxied
* replayable
* reportability
* retriable
* submittability
* throwables
* uat
* xquery

Is it possible to add them or use better dictionary?

**Comment by webdizz** [comment]
Thanks for pointing this out, added mentioned words + some other words check in version 0.1.98.
Also there is an ability to add words directly to the dictionary from the issue.

**Comment by mkordas** [comment]
Thanks @webdizz! I know that I can add words by myself, but it's a bit annoying when I need to add manually that are valid English words or they are commonly used in IT.
Have you considered running it e.g. for Spring and Guava projects and adding all false-positivies to dictionary?

**Comment by webdizz** [comment]
Good idea, thanks.
