### ISSUE TITLE
Violations triggered on date formats

### ISSUE THREAD

**Issue by mkordas** [webdizz/sonarqube-spellcheck#22]
In my project I use various date formats provided as strings, for example:
* yyyyMMdd
* ddMMyyyy
* yyyy-MM-dd
* yyyy-MM-dd'T'hh:mm:ss z
More examples can be found on page: https://docs.oracle.com/javase/tutorial/i18n/format/simpleDateFormat.html

Majority of them cause spellcheck violations right now, but I don't think it should be the case. 

Also, instead of getting violation just for `yyyy`, I get `yyyyMM` instead.

**Comment by webdizz** [comment]
Right, agree with your suggestion. Will spend some time to figure out how to exclude such things, meanwhile added more words to dictionary check the latest version.
