### ISSUE TITLE
Add new words to dictionary

### ISSUE THREAD

**Issue by mkordas** [webdizz/sonarqube-spellcheck#52]
Please make sure that all words from the following sources are added to the plugin's dictionary:
* https://github.com/JetBrains/intellij-community/blob/master/spellchecker/src/com/intellij/spellchecker/english.dic
* https://github.com/JetBrains/intellij-community/blob/master/spellchecker/src/com/intellij/spellchecker/jetbrains.dic

Also, I've found a few interesting dictionaries on GitHub. Words there are very valuable, but probably need some manual review if they really belong to dictionary:
* https://github.com/durbs182/SpellCheck/blob/b5aac8c4668305594be0a59c11c642bd7d474f90/NetSpellSpellCheck.SpellingEngine.Plugin/dictionaries/citrix.dic
* https://github.com/JetBrains/intellij-scala/blob/a20676a95edff3cca8fc29b225b2ea1bcadd07aa/resources/org/jetbrains/plugins/scala/spellchecker/scala.dic
* https://github.com/ccavanaugh/jgnash/blob/5344c8c74201fffd72dbb4b6d3a2845a05ad116f/spelling.dic
* https://github.com/waded/red-squiggly-braces/blob/9f09fc36b581f07c8cc04f40496061acf9a95e05/red-squiggly-braces.dic
* https://github.com/thegreymatter/CodeSpell/blob/c0385dba7c9ed3cbb65c69cecb779379167a483c/CodeSpell.Tests/dic/custom.dic
* https://github.com/mcasperson/ace-editor-expirments/blob/2bd7a015ebfa3a029d3fe3404b726c2745a93fe6/ace-demo/typojs/en_US-custom.dic

**Comment by webdizz** [comment]
Words were added

**Comment by mkordas** [comment]
@webdizz, thanks, but I've noticed that you've added all words from https://github.com/ccavanaugh/jgnash/blob/5344c8c74201fffd72dbb4b6d3a2845a05ad116f/spelling.dic without any manual verifiation. That was not the intention. I don't think that for example `AVAILBAL` is valid word.
